### ISSUE TITLE
curl problems with Win10

### ISSUE THREAD

**Issue by Bobobel** [airborneastro/photovoltaics#2]
Dear airborneastro,

I tried your curl commands, all modifications end up with {"err":404}.
Soe server adressing is OK, user and pass should be OK, because I can login directly into my 192.168.178.30.
The original POST with my credentials ended with
curl: (6) Could not resolve host: sma....            #   Remark: it was unclear, if this should be hex or long int. long worked
curl: (6) Could not resolve host: application
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) unmatched close brace/bracket in URL position 13: ..... # Remark: {} is not working in a win console!

I tried:
curl -v -k -H "Content-Type: application/json" -d "right=usr" -d "pass=****" https://sma&'long SN'/dyn/login.json
This is my shortest entry (**** replaced with my pass):
curl -k --json 'right=usr' --json 'pass=****'  https://192.168.178.30/dyn/login.json
But still I got "404"
Any idea ?

I tried a lot other stuff but all failed up today

**Comment by airborneastro** [comment]
The curl syntax is meant for a linux environment and it works there. You might want to find out what the difference in syntax is for Windows.

**Comment by airborneastro** [comment]
A quick google search results in finding that Windows (-curl) does not work with single quotes. You probably need to replace all single quotes with double quotes and escape the double quotes in the strings as in 
`-d "{\"right\":`  .....
